export const ALL_PRODUCTS_REQUEST = 'ALL_PRODUCTS_REQUEST'
export const ALL_PRODUCTS_SUCCESS = 'ALL_PRODUCTS_SUCCESS'
export const ALL_PRODUCTS_FAIL = 'ALL_PRODUCTS_FAIL'

export const PRODUCT_FEATURED_REQUEST = 'PRODUCT_FEATURED_REQUEST'
export const PRODUCT_FEATURED_SUCCESS = 'PRODUCT_FEATURED_SUCCESS'
export const PRODUCT_FEATURED_FAIL = 'PRODUCT_FEATURED_FAIL'

export const PRODUCT_LATEST_REQUEST = 'PRODUCT_LATEST_REQUEST'
export const PRODUCT_LATEST_SUCCESS = 'PRODUCT_LATEST_SUCCESS'
export const PRODUCT_LATEST_FAIL = 'PRODUCT_LATEST_FAIL'

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'

