export const CREATE_RECEIPT_REQUEST = 'CREATE_RECEIPT_REQUEST'
export const CREATE_RECEIPT_SUCCESS = 'CREATE_RECEIPT_SUCCESS'
export const CREATE_RECEIPT_FAIL = 'CREATE_RECEIPT_FAIL'

export const ALL_RECEIPTS_REQUEST = 'ALL_RECEIPTS_REQUEST'
export const ALL_RECEIPTS_SUCCESS = 'ALL_RECEIPTS_SUCCESS'
export const ALL_RECEIPTS_FAIL = 'ALL_RECEIPTS_FAIL'

export const RECEIPT_DETAILS_REQUEST = 'RECEIPT_DETAILS_REQUEST'
export const RECEIPT_DETAILS_SUCCESS = 'RECEIPT_DETAILS_SUCCESS'
export const RECEIPT_DETAILS_FAIL = 'RECEIPT_DETAILS_FAIL'

export const ADD_TO_RECEIPT = 'ADD_TO_RECEIPT'
export const REMOVE_ITEM_RECEIPT = 'REMOVE_ITEM_RECEIPT'
export const UPDATE_TO_RECEIPT = 'UPDATE_TO_RECEIPT'
export const RECEIPT_RESET = 'RECEIPT_RESET'
export const RECEIPT_IMPORT = 'RECEIPT_IMPORT'
export const SAVE_SUPPLIER_INFO = 'SAVE_SUPPLIER_INFO'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'